// ─── Item Registry ───
// Complete registry of all 89 items in Lineremain

import type { ItemDefinition } from '../types/items.js';
import { EquipSlot, ItemCategory } from '../types/items.js';

export const ITEM_REGISTRY: Record<number, ItemDefinition> = {
  // ═══════════════════════════════════════
  // RESOURCES (1-15)
  // ═══════════════════════════════════════
  1: {
    id: 1,
    name: 'Wood',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Raw wood harvested from trees.',
  },
  2: {
    id: 2,
    name: 'Stone',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Raw stone mined from rocks.',
  },
  3: {
    id: 3,
    name: 'Metal Ore',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Unrefined metal ore. Smelt in a furnace.',
  },
  4: {
    id: 4,
    name: 'Sulfur Ore',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Unrefined sulfur ore. Smelt in a furnace.',
  },
  5: {
    id: 5,
    name: 'HQM Ore',
    category: ItemCategory.Resource,
    maxStack: 100,
    description: 'High quality metal ore. Very rare.',
  },
  6: {
    id: 6,
    name: 'Cloth',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Cloth gathered from hemp plants.',
  },
  7: {
    id: 7,
    name: 'Leather',
    category: ItemCategory.Resource,
    maxStack: 500,
    description: 'Leather obtained from animals.',
  },
  8: {
    id: 8,
    name: 'Animal Fat',
    category: ItemCategory.Resource,
    maxStack: 500,
    description: 'Fat rendered from animal carcasses.',
  },
  9: {
    id: 9,
    name: 'Bone',
    category: ItemCategory.Resource,
    maxStack: 500,
    description: 'Bones collected from animal remains.',
  },
  10: {
    id: 10,
    name: 'Metal Fragments',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Refined metal fragments.',
  },
  11: {
    id: 11,
    name: 'Sulfur',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Refined sulfur powder.',
  },
  12: {
    id: 12,
    name: 'HQM',
    category: ItemCategory.Resource,
    maxStack: 100,
    description: 'High quality metal ingots.',
  },
  13: {
    id: 13,
    name: 'Charcoal',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Charcoal produced by burning wood.',
  },
  14: {
    id: 14,
    name: 'Gunpowder',
    category: ItemCategory.Resource,
    maxStack: 500,
    description: 'Explosive powder made from sulfur and charcoal.',
  },
  15: {
    id: 15,
    name: 'Low Grade Fuel',
    category: ItemCategory.Resource,
    maxStack: 500,
    description: 'Fuel made from animal fat and cloth.',
  },

  // ═══════════════════════════════════════
  // COMPONENTS (16-20)
  // ═══════════════════════════════════════
  16: {
    id: 16,
    name: 'Rope',
    category: ItemCategory.Component,
    maxStack: 100,
    description: 'Rope crafted from cloth.',
  },
  17: {
    id: 17,
    name: 'Tarp',
    category: ItemCategory.Component,
    maxStack: 50,
    description: 'Waterproof tarp made from cloth.',
  },
  18: {
    id: 18,
    name: 'Spring',
    category: ItemCategory.Component,
    maxStack: 50,
    description: 'Metal spring component.',
  },
  19: {
    id: 19,
    name: 'Pipe',
    category: ItemCategory.Component,
    maxStack: 50,
    description: 'Metal pipe component.',
  },
  20: {
    id: 20,
    name: 'Sewing Kit',
    category: ItemCategory.Component,
    maxStack: 50,
    description: 'Kit for crafting clothing and armor.',
  },

  // ═══════════════════════════════════════
  // TOOLS (21-28)
  // ═══════════════════════════════════════
  21: {
    id: 21,
    name: 'Rock',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'A basic rock. Can be used to gather resources.',
    durability: 50,
    damage: 5,
    gatherMultiplier: 1.0,
    equipSlot: EquipSlot.Held,
  },
  22: {
    id: 22,
    name: 'Stone Hatchet',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'A crude hatchet for chopping wood.',
    durability: 150,
    damage: 10,
    gatherMultiplier: 2.0,
    toolType: 'axe',
    equipSlot: EquipSlot.Held,
  },
  23: {
    id: 23,
    name: 'Stone Pickaxe',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'A crude pickaxe for mining stone and ore.',
    durability: 150,
    damage: 10,
    gatherMultiplier: 2.0,
    toolType: 'pickaxe',
    equipSlot: EquipSlot.Held,
  },
  24: {
    id: 24,
    name: 'Metal Hatchet',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'A sturdy hatchet for efficient wood gathering.',
    durability: 300,
    damage: 15,
    gatherMultiplier: 4.0,
    toolType: 'axe',
    equipSlot: EquipSlot.Held,
  },
  25: {
    id: 25,
    name: 'Metal Pickaxe',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'A sturdy pickaxe for efficient mining.',
    durability: 300,
    damage: 15,
    gatherMultiplier: 4.0,
    toolType: 'pickaxe',
    equipSlot: EquipSlot.Held,
  },
  26: {
    id: 26,
    name: 'Salvaged Axe',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'High-end axe made from salvaged parts.',
    durability: 500,
    damage: 20,
    gatherMultiplier: 6.0,
    toolType: 'axe',
    equipSlot: EquipSlot.Held,
  },
  27: {
    id: 27,
    name: 'Salvaged Icepick',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'High-end pickaxe made from salvaged parts.',
    durability: 500,
    damage: 20,
    gatherMultiplier: 6.0,
    toolType: 'pickaxe',
    equipSlot: EquipSlot.Held,
  },
  28: {
    id: 28,
    name: 'Hammer',
    category: ItemCategory.Tool,
    maxStack: 1,
    description: 'Used to build and repair structures.',
    durability: 500,
    damage: 5,
    equipSlot: EquipSlot.Held,
  },

  // ═══════════════════════════════════════
  // MELEE WEAPONS (29-34)
  // ═══════════════════════════════════════
  29: {
    id: 29,
    name: 'Bone Knife',
    category: ItemCategory.WeaponMelee,
    maxStack: 1,
    description: 'A crude knife made from bone.',
    durability: 100,
    damage: 15,
    equipSlot: EquipSlot.Held,
  },
  30: {
    id: 30,
    name: 'Stone Spear',
    category: ItemCategory.WeaponMelee,
    maxStack: 1,
    description: 'A spear tipped with sharpened stone.',
    durability: 150,
    damage: 20,
    equipSlot: EquipSlot.Held,
  },
  31: {
    id: 31,
    name: 'Wooden Spear',
    category: ItemCategory.WeaponMelee,
    maxStack: 1,
    description: 'A sharpened wooden spear.',
    durability: 100,
    damage: 15,
    equipSlot: EquipSlot.Held,
  },
  32: {
    id: 32,
    name: 'Machete',
    category: ItemCategory.WeaponMelee,
    maxStack: 1,
    description: 'A sharp metal blade for close combat.',
    durability: 250,
    damage: 30,
    equipSlot: EquipSlot.Held,
  },
  33: {
    id: 33,
    name: 'Salvaged Sword',
    category: ItemCategory.WeaponMelee,
    maxStack: 1,
    description: 'A heavy sword forged from salvaged metal.',
    durability: 400,
    damage: 40,
    equipSlot: EquipSlot.Held,
  },
  34: {
    id: 34,
    name: 'Bone Club',
    category: ItemCategory.WeaponMelee,
    maxStack: 1,
    description: 'A heavy club made from animal bone.',
    durability: 120,
    damage: 18,
    equipSlot: EquipSlot.Held,
  },

  // ═══════════════════════════════════════
  // RANGED WEAPONS (35-40)
  // ═══════════════════════════════════════
  35: {
    id: 35,
    name: 'Hunting Bow',
    category: ItemCategory.WeaponRanged,
    maxStack: 1,
    description: 'A simple bow for hunting and combat.',
    durability: 200,
    damage: 25,
    equipSlot: EquipSlot.Held,
  },
  36: {
    id: 36,
    name: 'Crossbow',
    category: ItemCategory.WeaponRanged,
    maxStack: 1,
    description: 'A powerful crossbow with slower reload.',
    durability: 300,
    damage: 40,
    equipSlot: EquipSlot.Held,
  },
  37: {
    id: 37,
    name: 'Revolver',
    category: ItemCategory.WeaponRanged,
    maxStack: 1,
    description: 'A simple six-shot revolver.',
    durability: 350,
    damage: 30,
    equipSlot: EquipSlot.Held,
  },
  38: {
    id: 38,
    name: 'Pipe Shotgun',
    category: ItemCategory.WeaponRanged,
    maxStack: 1,
    description: 'A crude single-shot shotgun.',
    durability: 200,
    damage: 60,
    equipSlot: EquipSlot.Held,
  },
  39: {
    id: 39,
    name: 'Semi-Auto Rifle',
    category: ItemCategory.WeaponRanged,
    maxStack: 1,
    description: 'A semi-automatic rifle.',
    durability: 400,
    damage: 35,
    equipSlot: EquipSlot.Held,
  },
  40: {
    id: 40,
    name: 'Assault Rifle',
    category: ItemCategory.WeaponRanged,
    maxStack: 1,
    description: 'A fully automatic assault rifle.',
    durability: 400,
    damage: 30,
    equipSlot: EquipSlot.Held,
  },

  // ═══════════════════════════════════════
  // AMMO (41-44)
  // ═══════════════════════════════════════
  41: {
    id: 41,
    name: 'Arrow',
    category: ItemCategory.Ammo,
    maxStack: 64,
    description: 'Standard wooden arrow.',
  },
  42: {
    id: 42,
    name: 'Pistol Ammo',
    category: ItemCategory.Ammo,
    maxStack: 128,
    description: 'Standard pistol ammunition.',
  },
  43: {
    id: 43,
    name: 'Shotgun Shell',
    category: ItemCategory.Ammo,
    maxStack: 64,
    description: 'Standard shotgun shell.',
  },
  44: {
    id: 44,
    name: 'Rifle Ammo',
    category: ItemCategory.Ammo,
    maxStack: 128,
    description: 'Standard rifle ammunition.',
  },

  // ═══════════════════════════════════════
  // ARMOR (45-52)
  // ═══════════════════════════════════════
  45: {
    id: 45,
    name: 'Burlap Shirt',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'A crude shirt offering minimal protection.',
    durability: 100,
    armorReduction: 5,
    equipSlot: EquipSlot.Chest,
  },
  46: {
    id: 46,
    name: 'Burlap Trousers',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'Crude trousers offering minimal protection.',
    durability: 100,
    armorReduction: 5,
    equipSlot: EquipSlot.Legs,
  },
  47: {
    id: 47,
    name: 'Hide Poncho',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'A leather poncho providing moderate protection.',
    durability: 200,
    armorReduction: 15,
    equipSlot: EquipSlot.Chest,
  },
  48: {
    id: 48,
    name: 'Hide Pants',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'Leather pants providing moderate protection.',
    durability: 200,
    armorReduction: 10,
    equipSlot: EquipSlot.Legs,
  },
  49: {
    id: 49,
    name: 'Hide Boots',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'Leather boots providing moderate protection.',
    durability: 200,
    armorReduction: 8,
    equipSlot: EquipSlot.Feet,
  },
  50: {
    id: 50,
    name: 'Road Sign Vest',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'A vest made from road signs. Good protection.',
    durability: 350,
    armorReduction: 30,
    equipSlot: EquipSlot.Chest,
  },
  51: {
    id: 51,
    name: 'Road Sign Kilt',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'Leg armor made from road signs.',
    durability: 350,
    armorReduction: 25,
    equipSlot: EquipSlot.Legs,
  },
  52: {
    id: 52,
    name: 'Metal Facemask',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'A metal facemask providing excellent head protection.',
    durability: 400,
    armorReduction: 40,
    equipSlot: EquipSlot.Head,
  },

  // ═══════════════════════════════════════
  // CONSUMABLES (53-59)
  // ═══════════════════════════════════════
  53: {
    id: 53,
    name: 'Raw Meat',
    category: ItemCategory.Consumable,
    maxStack: 20,
    description: 'Uncooked meat. Eating raw may cause food poisoning.',
    hungerRestore: 30,
    thirstRestore: 0,
  },
  54: {
    id: 54,
    name: 'Cooked Meat',
    category: ItemCategory.Consumable,
    maxStack: 20,
    description: 'Cooked meat. Safe to eat.',
    hungerRestore: 80,
    thirstRestore: 0,
  },
  55: {
    id: 55,
    name: 'Mushroom',
    category: ItemCategory.Consumable,
    maxStack: 20,
    description: 'A foraged mushroom. Slightly nutritious.',
    hungerRestore: 15,
    thirstRestore: 5,
  },
  56: {
    id: 56,
    name: 'Cactus Flesh',
    category: ItemCategory.Consumable,
    maxStack: 20,
    description: 'Moist cactus flesh. Provides some hydration.',
    hungerRestore: 10,
    thirstRestore: 30,
  },
  57: {
    id: 57,
    name: 'Water Jug',
    category: ItemCategory.Consumable,
    maxStack: 1,
    description: 'A jug of clean water.',
    hungerRestore: 0,
    thirstRestore: 100,
    durability: 5,
  },
  58: {
    id: 58,
    name: 'Bandage',
    category: ItemCategory.Consumable,
    maxStack: 5,
    description: 'A cloth bandage. Restores a small amount of health.',
    healAmount: 15,
  },
  59: {
    id: 59,
    name: 'Medical Syringe',
    category: ItemCategory.Consumable,
    maxStack: 3,
    description: 'A medical syringe. Restores significant health.',
    healAmount: 50,
  },

  // ═══════════════════════════════════════
  // BUILDING ITEMS (60-63)
  // ═══════════════════════════════════════
  60: {
    id: 60,
    name: 'Building Plan',
    category: ItemCategory.Building,
    maxStack: 1,
    description: 'Used to place twig building pieces.',
    durability: 9999,
    equipSlot: EquipSlot.Held,
  },
  61: {
    id: 61,
    name: 'Wooden Door',
    category: ItemCategory.Building,
    maxStack: 5,
    description: 'A wooden door for doorways.',
  },
  62: {
    id: 62,
    name: 'Metal Door',
    category: ItemCategory.Building,
    maxStack: 5,
    description: 'A reinforced metal door.',
  },
  63: {
    id: 63,
    name: 'Code Lock',
    category: ItemCategory.Building,
    maxStack: 5,
    description: 'A code lock to secure doors and containers.',
  },

  // ═══════════════════════════════════════
  // DEPLOYABLES (64-67)
  // ═══════════════════════════════════════
  64: {
    id: 64,
    name: 'Sleeping Bag',
    category: ItemCategory.Deployable,
    maxStack: 3,
    description: 'Place to set a respawn point.',
  },
  65: {
    id: 65,
    name: 'Small Stash',
    category: ItemCategory.Deployable,
    maxStack: 3,
    description: 'A hidden stash container buried in the ground.',
  },
  66: {
    id: 66,
    name: 'Camp Fire',
    category: ItemCategory.Deployable,
    maxStack: 3,
    description: 'Provides warmth and allows cooking.',
  },
  67: {
    id: 67,
    name: 'Furnace',
    category: ItemCategory.Deployable,
    maxStack: 1,
    description: 'Smelts ores into refined materials.',
  },

  // ═══════════════════════════════════════
  // JOURNAL FRAGMENTS (68-87)
  // ═══════════════════════════════════════
  68: {
    id: 68,
    name: 'Journal Fragment #1',
    category: ItemCategory.Resource,
    maxStack: 1,
    description: 'A weathered page. "Day 1 — The line holds. We built the wall higher today..."',
  },
  69: {
    id: 69,
    name: 'Journal Fragment #2',
    category: ItemCategory.Resource,
    maxStack: 1,
    description: 'A torn page. "Day 14 — They come every night now. The husks never tire..."',
  },
  70: {
    id: 70,
    name: 'Journal Fragment #3',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A stained page. "Day 23 — Lost two more. Maria says we should abandon the east tower..."',
  },
  71: {
    id: 71,
    name: 'Journal Fragment #4',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A crumpled page. "Day 31 — The blood moon rose again. Fourth time. They brought something new..."',
  },
  72: {
    id: 72,
    name: 'Journal Fragment #5',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A faded page. "Day 40 — Found the old supply cache in the forest. Enough ammo for a week..."',
  },
  73: {
    id: 73,
    name: 'Journal Fragment #6',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A damp page. "Day 45 — The fog rolled in thick today. Could barely see the wall..."',
  },
  74: {
    id: 74,
    name: 'Journal Fragment #7',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A brittle page. "Day 52 — The cold ones appeared in the northern peaks. Blue eyes in the blizzard..."',
  },
  75: {
    id: 75,
    name: 'Journal Fragment #8',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A bloodstained page. "Day 58 — They breached the western section. We held, barely..."',
  },
  76: {
    id: 76,
    name: 'Journal Fragment #9',
    category: ItemCategory.Resource,
    maxStack: 1,
    description: 'A charred page. "Day 63 — Lit a signal fire. No one came. Are we the last ones?"',
  },
  77: {
    id: 77,
    name: 'Journal Fragment #10',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A carefully folded page. "Day 70 — Three camps spotted to the south. Others survived..."',
  },
  78: {
    id: 78,
    name: 'Journal Fragment #11',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A water-damaged page. "Day 75 — The swamp creatures are the worst. You can hear them before you see them..."',
  },
  79: {
    id: 79,
    name: 'Journal Fragment #12',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A page wrapped in cloth. "Day 82 — Found an old armory. The metal doors still hold..."',
  },
  80: {
    id: 80,
    name: 'Journal Fragment #13',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A scrawled page. "Day 89 — The dust hoppers are friendly if you don\'t startle them..."',
  },
  81: {
    id: 81,
    name: 'Journal Fragment #14',
    category: ItemCategory.Resource,
    maxStack: 1,
    description: 'A page with a crude map. "Day 94 — Mapped the safe routes between the camps..."',
  },
  82: {
    id: 82,
    name: 'Journal Fragment #15',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A hastily written page. "Day 100 — Centennial. Still standing. The line remains..."',
  },
  83: {
    id: 83,
    name: 'Journal Fragment #16',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A formal-looking page. "Day 107 — Established trade with the harbor settlement..."',
  },
  84: {
    id: 84,
    name: 'Journal Fragment #17',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A page torn from a notebook. "Day 115 — The brutes grow larger. Something is changing them..."',
  },
  85: {
    id: 85,
    name: 'Journal Fragment #18',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A carefully preserved page. "Day 120 — Recording everything for those who come after..."',
  },
  86: {
    id: 86,
    name: 'Journal Fragment #19',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'A page sealed with wax. "Day 130 — If you find this, know that we tried. We held the line..."',
  },
  87: {
    id: 87,
    name: 'Journal Fragment #20',
    category: ItemCategory.Resource,
    maxStack: 1,
    description:
      'The final page. "Day 142 — This is the last entry. The wall stands. Someone must continue..."',
  },

  // ═══════════════════════════════════════
  // CREATURE DROPS (88-89)
  // ═══════════════════════════════════════
  88: {
    id: 88,
    name: 'Frost Fang',
    category: ItemCategory.Resource,
    maxStack: 10,
    description: 'A razor-sharp tooth from a Frost Stalker. Cold to the touch.',
  },
  89: {
    id: 89,
    name: 'Crimson Core',
    category: ItemCategory.Resource,
    maxStack: 5,
    description: 'A pulsing organ from a Crimson Husk. Radiates faint heat.',
  },

  // ═══════════════════════════════════════
  // ENDGAME ITEMS (90-96)
  // ═══════════════════════════════════════
  90: {
    id: 90,
    name: 'C4 Explosive',
    category: ItemCategory.Deployable,
    maxStack: 5,
    description: 'Timed explosive. Place on enemy buildings to breach walls.',
  },
  91: {
    id: 91,
    name: 'Storage Box',
    category: ItemCategory.Deployable,
    maxStack: 5,
    description: 'A wooden container with 12 storage slots.',
  },
  92: {
    id: 92,
    name: 'Large Storage Box',
    category: ItemCategory.Deployable,
    maxStack: 3,
    description: 'A large wooden container with 24 storage slots.',
  },
  93: {
    id: 93,
    name: 'Landmine',
    category: ItemCategory.Deployable,
    maxStack: 10,
    description: 'Proximity-triggered explosive. Arms after 5 seconds.',
  },
  94: {
    id: 94,
    name: 'Wooden Barricade',
    category: ItemCategory.Building,
    maxStack: 10,
    description: 'A defensive barrier. Blocks movement.',
  },
  95: {
    id: 95,
    name: 'Research Table',
    category: ItemCategory.Deployable,
    maxStack: 1,
    description: 'Use scrap to research items and learn their blueprints.',
  },
  96: {
    id: 96,
    name: 'Scrap',
    category: ItemCategory.Resource,
    maxStack: 1000,
    description: 'Salvaged material used for research.',
  },

  // ═══════════════════════════════════════
  // ISLAND ITEMS (97-103)
  // ═══════════════════════════════════════
  97: {
    id: 97,
    name: 'Wild Berry',
    category: ItemCategory.Consumable,
    maxStack: 20,
    description: 'Sweet berries foraged from island bushes.',
    hungerRestore: 8,
    thirstRestore: 5,
  },
  98: {
    id: 98,
    name: 'Mushroom Stew',
    category: ItemCategory.Consumable,
    maxStack: 5,
    description: 'A hearty stew made from mushrooms. Very nourishing.',
    hungerRestore: 25,
    thirstRestore: 15,
    healAmount: 5,
  },
  99: {
    id: 99,
    name: 'Water Flask',
    category: ItemCategory.Consumable,
    maxStack: 5,
    description: 'A flask of fresh water.',
    hungerRestore: 0,
    thirstRestore: 30,
  },
  100: {
    id: 100,
    name: 'Torch',
    category: ItemCategory.Tool,
    maxStack: 5,
    description: 'A burning torch. Provides light.',
    durability: 100,
    damage: 5,
    equipSlot: EquipSlot.Held,
  },
  101: {
    id: 101,
    name: 'Fiber Rope',
    category: ItemCategory.Component,
    maxStack: 20,
    description: 'Strong rope woven from plant fibers.',
  },
  102: {
    id: 102,
    name: 'Stone Knife',
    category: ItemCategory.WeaponMelee,
    maxStack: 1,
    description: 'A crude knife chipped from stone.',
    durability: 100,
    damage: 15,
    equipSlot: EquipSlot.Held,
  },
  103: {
    id: 103,
    name: 'Wooden Shield',
    category: ItemCategory.Armor,
    maxStack: 1,
    description: 'A rough shield made from planks and rope.',
    durability: 150,
    armorReduction: 10,
    equipSlot: EquipSlot.Held,
  },
};
